language: php

matrix:
  fast_finish: true

  include:
    - os: linux
      php: '7.2'

cache:
  directories:
    - $HOME/.composer/cache

install:
  - pip install --user awscli
  - pip install --user aws-sam-cli
  - composer install

script:
  - composer build

deploy:
  provider: script
  script: bin/deploy.sh
  skip_cleanup: true
  on:
    branch: master
